# Azure Function


pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Pay-As-You-Go (f65cdc03-dc4a-4d97-9023-7dce649f899b)'
    appType: 'functionApp'
    appName: 'currate-fn-dev-ne'